### ISSUE TITLE
Ability to process Images

### ISSUE THREAD

**Issue by vbsoni** [jfrazee/nifi-tika-bundle#2]
Hi,

        Is it possible to add functionality to process images also available in pdfs?

**Comment by jfrazee** [comment]
@vbsoni Can you elaborate on what this would mean? Are you thinking extracting metadata from embedded images or something more sophisticated like OCR from mixed media PDFs?

**Comment by vbsoni** [comment]
@jfrazee 
I have several pdfs inside them entire content available as set of images only. Like someone generated using any scrapping tool. I want to extract text out of those images. 

I was able to write a small program using tesseract-ocr in my eclipse but I want to use it inside NiFi. 
 
Attaching my small program written as maven project in eclipse. 

Appreciate if you could integrate the same with NiFi.
[ImageConverter.zip](https://github.com/jfrazee/nifi-tika-bundle/files/662710/ImageConverter.zip)


.

**Comment by vbsoni** [comment]
@jfrazee I think we already have tesseract processor for nifi.

https://github.com/jdye64/nifi-addons/tree/master/Processors/nifi-tesseract

:)

**Comment by jfrazee** [comment]
@vbsoni Yes, that's correct. If you need OCR, I'd say to go with jdye64's work. Tesseract is a bit heavier than vanilla Tika, so I haven't really been envisioning adding all that into the nifi-tika-bundle.

**Comment by jfrazee** [comment]
@vbsoni Closing this. Do feel free to re-open if you decide/think/want to further discuss if this bundle should still be enhanced.
